# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /code/sourcecode/live-rusty-cat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /code/sourcecode/live-rusty-cat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /code/sourcecode/live-rusty-cat/CMakeFiles /code/sourcecode/live-rusty-cat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /code/sourcecode/live-rusty-cat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named output/rtmp-publish

# Build rule for target.
output/rtmp-publish: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output/rtmp-publish
.PHONY : output/rtmp-publish

# fast build rule for target.
output/rtmp-publish/fast:
	$(MAKE) -f CMakeFiles/output/rtmp-publish.dir/build.make CMakeFiles/output/rtmp-publish.dir/build
.PHONY : output/rtmp-publish/fast

#=============================================================================
# Target rules for targets named rtmp

# Build rule for target.
rtmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtmp
.PHONY : rtmp

# fast build rule for target.
rtmp/fast:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/build
.PHONY : rtmp/fast

#=============================================================================
# Target rules for targets named output/rtmp-play

# Build rule for target.
output/rtmp-play: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output/rtmp-play
.PHONY : output/rtmp-play

# fast build rule for target.
output/rtmp-play/fast:
	$(MAKE) -f CMakeFiles/output/rtmp-play.dir/build.make CMakeFiles/output/rtmp-play.dir/build
.PHONY : output/rtmp-play/fast

libs/app/hdl.o: libs/app/hdl.cpp.o

.PHONY : libs/app/hdl.o

# target to build an object file
libs/app/hdl.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/app/hdl.cpp.o
.PHONY : libs/app/hdl.cpp.o

libs/app/hdl.i: libs/app/hdl.cpp.i

.PHONY : libs/app/hdl.i

# target to preprocess a source file
libs/app/hdl.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/app/hdl.cpp.i
.PHONY : libs/app/hdl.cpp.i

libs/app/hdl.s: libs/app/hdl.cpp.s

.PHONY : libs/app/hdl.s

# target to generate assembly for a file
libs/app/hdl.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/app/hdl.cpp.s
.PHONY : libs/app/hdl.cpp.s

libs/basic/buffer.o: libs/basic/buffer.cpp.o

.PHONY : libs/basic/buffer.o

# target to build an object file
libs/basic/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/buffer.cpp.o
.PHONY : libs/basic/buffer.cpp.o

libs/basic/buffer.i: libs/basic/buffer.cpp.i

.PHONY : libs/basic/buffer.i

# target to preprocess a source file
libs/basic/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/buffer.cpp.i
.PHONY : libs/basic/buffer.cpp.i

libs/basic/buffer.s: libs/basic/buffer.cpp.s

.PHONY : libs/basic/buffer.s

# target to generate assembly for a file
libs/basic/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/buffer.cpp.s
.PHONY : libs/basic/buffer.cpp.s

libs/basic/file.o: libs/basic/file.cpp.o

.PHONY : libs/basic/file.o

# target to build an object file
libs/basic/file.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/file.cpp.o
.PHONY : libs/basic/file.cpp.o

libs/basic/file.i: libs/basic/file.cpp.i

.PHONY : libs/basic/file.i

# target to preprocess a source file
libs/basic/file.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/file.cpp.i
.PHONY : libs/basic/file.cpp.i

libs/basic/file.s: libs/basic/file.cpp.s

.PHONY : libs/basic/file.s

# target to generate assembly for a file
libs/basic/file.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/file.cpp.s
.PHONY : libs/basic/file.cpp.s

libs/basic/io.o: libs/basic/io.cpp.o

.PHONY : libs/basic/io.o

# target to build an object file
libs/basic/io.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/io.cpp.o
.PHONY : libs/basic/io.cpp.o

libs/basic/io.i: libs/basic/io.cpp.i

.PHONY : libs/basic/io.i

# target to preprocess a source file
libs/basic/io.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/io.cpp.i
.PHONY : libs/basic/io.cpp.i

libs/basic/io.s: libs/basic/io.cpp.s

.PHONY : libs/basic/io.s

# target to generate assembly for a file
libs/basic/io.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/basic/io.cpp.s
.PHONY : libs/basic/io.cpp.s

libs/container/flv.o: libs/container/flv.cpp.o

.PHONY : libs/container/flv.o

# target to build an object file
libs/container/flv.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/container/flv.cpp.o
.PHONY : libs/container/flv.cpp.o

libs/container/flv.i: libs/container/flv.cpp.i

.PHONY : libs/container/flv.i

# target to preprocess a source file
libs/container/flv.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/container/flv.cpp.i
.PHONY : libs/container/flv.cpp.i

libs/container/flv.s: libs/container/flv.cpp.s

.PHONY : libs/container/flv.s

# target to generate assembly for a file
libs/container/flv.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/container/flv.cpp.s
.PHONY : libs/container/flv.cpp.s

libs/http_parser.o: libs/http_parser.c.o

.PHONY : libs/http_parser.o

# target to build an object file
libs/http_parser.c.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/http_parser.c.o
.PHONY : libs/http_parser.c.o

libs/http_parser.i: libs/http_parser.c.i

.PHONY : libs/http_parser.i

# target to preprocess a source file
libs/http_parser.c.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/http_parser.c.i
.PHONY : libs/http_parser.c.i

libs/http_parser.s: libs/http_parser.c.s

.PHONY : libs/http_parser.s

# target to generate assembly for a file
libs/http_parser.c.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/http_parser.c.s
.PHONY : libs/http_parser.c.s

libs/logs/log.o: libs/logs/log.cpp.o

.PHONY : libs/logs/log.o

# target to build an object file
libs/logs/log.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/logs/log.cpp.o
.PHONY : libs/logs/log.cpp.o

libs/logs/log.i: libs/logs/log.cpp.i

.PHONY : libs/logs/log.i

# target to preprocess a source file
libs/logs/log.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/logs/log.cpp.i
.PHONY : libs/logs/log.cpp.i

libs/logs/log.s: libs/logs/log.cpp.s

.PHONY : libs/logs/log.s

# target to generate assembly for a file
libs/logs/log.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/logs/log.cpp.s
.PHONY : libs/logs/log.cpp.s

libs/protocol/http.o: libs/protocol/http.cpp.o

.PHONY : libs/protocol/http.o

# target to build an object file
libs/protocol/http.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/protocol/http.cpp.o
.PHONY : libs/protocol/http.cpp.o

libs/protocol/http.i: libs/protocol/http.cpp.i

.PHONY : libs/protocol/http.i

# target to preprocess a source file
libs/protocol/http.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/protocol/http.cpp.i
.PHONY : libs/protocol/http.cpp.i

libs/protocol/http.s: libs/protocol/http.cpp.s

.PHONY : libs/protocol/http.s

# target to generate assembly for a file
libs/protocol/http.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/protocol/http.cpp.s
.PHONY : libs/protocol/http.cpp.s

libs/protocol/rtmp.o: libs/protocol/rtmp.cpp.o

.PHONY : libs/protocol/rtmp.o

# target to build an object file
libs/protocol/rtmp.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/protocol/rtmp.cpp.o
.PHONY : libs/protocol/rtmp.cpp.o

libs/protocol/rtmp.i: libs/protocol/rtmp.cpp.i

.PHONY : libs/protocol/rtmp.i

# target to preprocess a source file
libs/protocol/rtmp.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/protocol/rtmp.cpp.i
.PHONY : libs/protocol/rtmp.cpp.i

libs/protocol/rtmp.s: libs/protocol/rtmp.cpp.s

.PHONY : libs/protocol/rtmp.s

# target to generate assembly for a file
libs/protocol/rtmp.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/protocol/rtmp.cpp.s
.PHONY : libs/protocol/rtmp.cpp.s

libs/rtmp_tool.o: libs/rtmp_tool.cpp.o

.PHONY : libs/rtmp_tool.o

# target to build an object file
libs/rtmp_tool.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/rtmp_tool.cpp.o
.PHONY : libs/rtmp_tool.cpp.o

libs/rtmp_tool.i: libs/rtmp_tool.cpp.i

.PHONY : libs/rtmp_tool.i

# target to preprocess a source file
libs/rtmp_tool.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/rtmp_tool.cpp.i
.PHONY : libs/rtmp_tool.cpp.i

libs/rtmp_tool.s: libs/rtmp_tool.cpp.s

.PHONY : libs/rtmp_tool.s

# target to generate assembly for a file
libs/rtmp_tool.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp.dir/build.make CMakeFiles/rtmp.dir/libs/rtmp_tool.cpp.s
.PHONY : libs/rtmp_tool.cpp.s

rtmp-play.o: rtmp-play.cpp.o

.PHONY : rtmp-play.o

# target to build an object file
rtmp-play.cpp.o:
	$(MAKE) -f CMakeFiles/output/rtmp-play.dir/build.make CMakeFiles/output/rtmp-play.dir/rtmp-play.cpp.o
.PHONY : rtmp-play.cpp.o

rtmp-play.i: rtmp-play.cpp.i

.PHONY : rtmp-play.i

# target to preprocess a source file
rtmp-play.cpp.i:
	$(MAKE) -f CMakeFiles/output/rtmp-play.dir/build.make CMakeFiles/output/rtmp-play.dir/rtmp-play.cpp.i
.PHONY : rtmp-play.cpp.i

rtmp-play.s: rtmp-play.cpp.s

.PHONY : rtmp-play.s

# target to generate assembly for a file
rtmp-play.cpp.s:
	$(MAKE) -f CMakeFiles/output/rtmp-play.dir/build.make CMakeFiles/output/rtmp-play.dir/rtmp-play.cpp.s
.PHONY : rtmp-play.cpp.s

rtmp-publish.o: rtmp-publish.cpp.o

.PHONY : rtmp-publish.o

# target to build an object file
rtmp-publish.cpp.o:
	$(MAKE) -f CMakeFiles/output/rtmp-publish.dir/build.make CMakeFiles/output/rtmp-publish.dir/rtmp-publish.cpp.o
.PHONY : rtmp-publish.cpp.o

rtmp-publish.i: rtmp-publish.cpp.i

.PHONY : rtmp-publish.i

# target to preprocess a source file
rtmp-publish.cpp.i:
	$(MAKE) -f CMakeFiles/output/rtmp-publish.dir/build.make CMakeFiles/output/rtmp-publish.dir/rtmp-publish.cpp.i
.PHONY : rtmp-publish.cpp.i

rtmp-publish.s: rtmp-publish.cpp.s

.PHONY : rtmp-publish.s

# target to generate assembly for a file
rtmp-publish.cpp.s:
	$(MAKE) -f CMakeFiles/output/rtmp-publish.dir/build.make CMakeFiles/output/rtmp-publish.dir/rtmp-publish.cpp.s
.PHONY : rtmp-publish.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... output/rtmp-publish"
	@echo "... rtmp"
	@echo "... output/rtmp-play"
	@echo "... libs/app/hdl.o"
	@echo "... libs/app/hdl.i"
	@echo "... libs/app/hdl.s"
	@echo "... libs/basic/buffer.o"
	@echo "... libs/basic/buffer.i"
	@echo "... libs/basic/buffer.s"
	@echo "... libs/basic/file.o"
	@echo "... libs/basic/file.i"
	@echo "... libs/basic/file.s"
	@echo "... libs/basic/io.o"
	@echo "... libs/basic/io.i"
	@echo "... libs/basic/io.s"
	@echo "... libs/container/flv.o"
	@echo "... libs/container/flv.i"
	@echo "... libs/container/flv.s"
	@echo "... libs/http_parser.o"
	@echo "... libs/http_parser.i"
	@echo "... libs/http_parser.s"
	@echo "... libs/logs/log.o"
	@echo "... libs/logs/log.i"
	@echo "... libs/logs/log.s"
	@echo "... libs/protocol/http.o"
	@echo "... libs/protocol/http.i"
	@echo "... libs/protocol/http.s"
	@echo "... libs/protocol/rtmp.o"
	@echo "... libs/protocol/rtmp.i"
	@echo "... libs/protocol/rtmp.s"
	@echo "... libs/rtmp_tool.o"
	@echo "... libs/rtmp_tool.i"
	@echo "... libs/rtmp_tool.s"
	@echo "... rtmp-play.o"
	@echo "... rtmp-play.i"
	@echo "... rtmp-play.s"
	@echo "... rtmp-publish.o"
	@echo "... rtmp-publish.i"
	@echo "... rtmp-publish.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

